<a href="https://colab.research.google.com/github/Nanthman2/Nanthman2/blob/main/Spark.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!apt-get install -y openjdk-8-jdk-headless -qq > /dev/null
!pip install -q pyspark

In [2]:
from pyspark import SparkContext
import os
sc = SparkContext.getOrCreate()
sc

In [3]:
import pyspark.sql.functions as F
from pyspark.sql.types import *

In [6]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[*]").appName("Colab").getOrCreate()
spark

In [7]:
schema = StructType().add("id_utilisateur", "string").add("pays", "string").add("profession", "string").add("genre", 'string').add("age", "integer")

In [11]:
df = spark.createDataFrame([("A123", 'Maroc', "Médecin", "Femme", 33), ("B234", 'Canada', "Entrepreneur", "Femme", 35), ("C345", 'France', "Professeur", "Homme", 41)],schema=schema)

In [12]:
df.printSchema()

root
 |-- id_utilisateur: string (nullable = true)
 |-- pays: string (nullable = true)
 |-- profession: string (nullable = true)
 |-- genre: string (nullable = true)
 |-- age: integer (nullable = true)

In [13]:
df.show()

+--------------+------+------------+-----+---+
|id_utilisateur|  pays|  profession|genre|age|
+--------------+------+------------+-----+---+
|          A123| Maroc|     Médecin|Femme| 33|
|          B234|Canada|Entrepreneur|Femme| 35|
|          C345|France|  Professeur|Homme| 41|
+--------------+------+------------+-----+---+

In [14]:
from google.colab import files
files.upload()

Saving 03_03_data.csv to 03_03_data.csv

{'03_03_data.csv': b'Pays;2005;2006;2007;2008;2009;2010;2011;2012;2013;2014;2015;2016;2017;2018\r\nAllemagne;7,20;8,50;10,10;10,10;10,90;11,70;12,50;13,60;13,80;14,40;14,90;14,90;15,50;16,50\r\nAutriche;24,40;26,30;28,20;28,90;31,00;31,20;31,60;32,70;32,80;33,70;33,50;33,40;33,10;33,40\r\nBelgique;2,30;2,60;3,10;3,60;4,70;5,60;6,30;7,20;7,50;8,00;8,00;8,70;9,10;9,40\r\nBulgarie;9,20;9,40;9,10;10,30;12,00;13,90;14,20;15,80;18,90;18,10;18,30;18,80;18,70;20,50\r\nChypre;3,10;3,30;4,00;5,10;5,90;6,20;6,30;7,10;8,50;9,20;9,90;9,90;10,50;13,90\r\nCroatie;23,70;22,70;22,20;22,00;23,60;25,10;25,40;26,80;28,00;27,80;29,00;28,30;27,30;28,00\r\nDanemark;16,00;16,30;17,70;18,50;20,00;21,90;23,40;25,50;27,20;29,30;30,80;31,80;34,70;35,70\r\nEspagne;8,40;9,10;9,70;10,70;13,00;13,80;13,20;14,30;15,30;16,10;16,20;17,40;17,60;17,50\r\nEstonie;17,40;16,00;17,00;18,60;22,90;24,60;25,30;25,50;25,30;26,10;28,20;28,70;29,10;30,00\r\nFinlande;28,80;30,10;29,60;31,40;31,30;32,40;32,80;34,40;36,70;38,80;39,30;39,00;40,90;41,20\r\nFrance;9,60;9,30;10,20;11,20;12,20;12,70;(1) 12,7;13,40;14,00;14,60;15,00;15,70;16,00;16,60\r\nGr\xe8ce;7,30;7,50;8,20;8,20;8,70;10,10;11,20;13,70;15,30;15,70;15,70;15,40;17,00;18,00\r\nHongrie;6,90;7,40;8,60;8,60;11,70;12,70;14,00;15,50;16,20;14,60;14,50;14,30;13,50;12,50\r\nIrlande;2,80;3,00;3,50;3,90;5,20;5,70;6,60;7,10;7,60;8,60;9,10;9,30;10,60;11,10\r\nItalie;7,50;8,30;9,80;11,50;12,80;13,00;12,90;15,40;16,70;17,10;17,50;17,40;18,30;17,80\r\nLettonie;32,30;31,10;29,60;29,80;34,30;30,40;33,50;35,70;37,00;38,60;37,50;37,10;39,00;40,30\r\nLituanie;16,80;16,90;16,50;17,80;19,80;19,60;19,90;21,40;22,70;23,60;25,80;25,60;26,00;24,40\r\nLuxembourg;1,40;1,50;2,70;2,80;2,90;2,90;2,90;3,10;3,50;4,50;5,10;5,40;6,30;9,10\r\nMalte;0,10;0,10;0,20;0,20;0,20;1,00;1,90;2,90;3,80;4,70;5,10;6,20;7,30;8,00\r\nPays-Bas;2,50;2,80;3,30;3,60;4,30;3,90;4,50;4,70;4,70;5,40;5,70;5,80;6,50;7,40\r\nPologne;6,90;6,90;6,90;7,70;8,70;9,30;10,30;10,90;11,40;11,50;11,70;11,30;11,00;11,30\r\nPortugal;19,50;20,80;21,90;22,90;24,40;24,20;24,60;24,60;25,70;29,50;30,50;30,90;30,60;30,30\r\nR\xe9publique tch\xe8que;7,10;7,40;7,90;8,70;10,00;10,50;10,90;12,80;13,90;15,10;15,10;14,90;14,80;15,20\r\nRoumanie;17,60;17,10;18,20;20,20;22,20;22,80;21,20;22,80;23,90;24,80;24,80;25,00;24,50;23,90\r\nRoyaume-Uni;1,10;1,30;1,60;2,70;3,30;3,80;4,30;4,40;5,50;6,70;8,30;9,00;9,70;11,00\r\nSlovaquie;6,40;6,60;7,80;7,70;9,40;9,10;10,30;10,50;10,10;11,70;12,90;12,00;11,50;11,90\r\nSlov\xe9nie;16,00;15,60;15,60;15,00;20,10;20,40;20,30;20,80;22,40;21,50;21,90;21,30;21,10;21,10\r\nSu\xe8de;40,70;42,40;43,90;44,70;47,90;47,00;48,20;50,20;50,80;51,90;53,00;53,40;54,20;54,60\r\n'}

In [16]:
df= spark.read.option("delimiter",";").csv("03_03_data.csv",header=True)
type(df)

pyspark.sql.classic.dataframe.DataFrame

In [17]:
df.show(5)

+---------+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
|     Pays| 2005| 2006| 2007| 2008| 2009| 2010| 2011| 2012| 2013| 2014| 2015| 2016| 2017| 2018|
+---------+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
|Allemagne| 7,20| 8,50|10,10|10,10|10,90|11,70|12,50|13,60|13,80|14,40|14,90|14,90|15,50|16,50|
| Autriche|24,40|26,30|28,20|28,90|31,00|31,20|31,60|32,70|32,80|33,70|33,50|33,40|33,10|33,40|
| Belgique| 2,30| 2,60| 3,10| 3,60| 4,70| 5,60| 6,30| 7,20| 7,50| 8,00| 8,00| 8,70| 9,10| 9,40|
| Bulgarie| 9,20| 9,40| 9,10|10,30|12,00|13,90|14,20|15,80|18,90|18,10|18,30|18,80|18,70|20,50|
|   Chypre| 3,10| 3,30| 4,00| 5,10| 5,90| 6,20| 6,30| 7,10| 8,50| 9,20| 9,90| 9,90|10,50|13,90|
+---------+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
only showing top 5 rows

In [18]:
df.count

<bound method DataFrame.count of DataFrame[Pays: string, 2005: string, 2006: string, 2007: string, 2008: string, 2009: string, 2010: string, 2011: string, 2012: string, 2013: string, 2014: string, 2015: string, 2016: string, 2017: string, 2018: string]>

In [19]:
len(df.columns)

15

In [20]:
df.take(2)

[Row(Pays='Allemagne', 2005='7,20', 2006='8,50', 2007='10,10', 2008='10,10', 2009='10,90', 2010='11,70', 2011='12,50', 2012='13,60', 2013='13,80', 2014='14,40', 2015='14,90', 2016='14,90', 2017='15,50', 2018='16,50'),
 Row(Pays='Autriche', 2005='24,40', 2006='26,30', 2007='28,20', 2008='28,90', 2009='31,00', 2010='31,20', 2011='31,60', 2012='32,70', 2013='32,80', 2014='33,70', 2015='33,50', 2016='33,40', 2017='33,10', 2018='33,40')]

In [22]:
df.collect()

[Row(Pays='Allemagne', 2005='7,20', 2006='8,50', 2007='10,10', 2008='10,10', 2009='10,90', 2010='11,70', 2011='12,50', 2012='13,60', 2013='13,80', 2014='14,40', 2015='14,90', 2016='14,90', 2017='15,50', 2018='16,50'),
 Row(Pays='Autriche', 2005='24,40', 2006='26,30', 2007='28,20', 2008='28,90', 2009='31,00', 2010='31,20', 2011='31,60', 2012='32,70', 2013='32,80', 2014='33,70', 2015='33,50', 2016='33,40', 2017='33,10', 2018='33,40'),
 Row(Pays='Belgique', 2005='2,30', 2006='2,60', 2007='3,10', 2008='3,60', 2009='4,70', 2010='5,60', 2011='6,30', 2012='7,20', 2013='7,50', 2014='8,00', 2015='8,00', 2016='8,70', 2017='9,10', 2018='9,40'),
 Row(Pays='Bulgarie', 2005='9,20', 2006='9,40', 2007='9,10', 2008='10,30', 2009='12,00', 2010='13,90', 2011='14,20', 2012='15,80', 2013='18,90', 2014='18,10', 2015='18,30', 2016='18,80', 2017='18,70', 2018='20,50'),
 Row(Pays='Chypre', 2005='3,10', 2006='3,30', 2007='4,00', 2008='5,10', 2009='5,90', 2010='6,20', 2011='6,30', 2012='7,10', 2013='8,50', 2014='9,20', 2015='9,90', 2016='9,90', 2017='10,50', 2018='13,90'),
 Row(Pays='Croatie', 2005='23,70', 2006='22,70', 2007='22,20', 2008='22,00', 2009='23,60', 2010='25,10', 2011='25,40', 2012='26,80', 2013='28,00', 2014='27,80', 2015='29,00', 2016='28,30', 2017='27,30', 2018='28,00'),
 Row(Pays='Danemark', 2005='16,00', 2006='16,30', 2007='17,70', 2008='18,50', 2009='20,00', 2010='21,90', 2011='23,40', 2012='25,50', 2013='27,20', 2014='29,30', 2015='30,80', 2016='31,80', 2017='34,70', 2018='35,70'),
 Row(Pays='Espagne', 2005='8,40', 2006='9,10', 2007='9,70', 2008='10,70', 2009='13,00', 2010='13,80', 2011='13,20', 2012='14,30', 2013='15,30', 2014='16,10', 2015='16,20', 2016='17,40', 2017='17,60', 2018='17,50'),
 Row(Pays='Estonie', 2005='17,40', 2006='16,00', 2007='17,00', 2008='18,60', 2009='22,90', 2010='24,60', 2011='25,30', 2012='25,50', 2013='25,30', 2014='26,10', 2015='28,20', 2016='28,70', 2017='29,10', 2018='30,00'),
 Row(Pays='Finlande', 2005='28,80', 2006='30,10', 2007='29,60', 2008='31,40', 2009='31,30', 2010='32,40', 2011='32,80', 2012='34,40', 2013='36,70', 2014='38,80', 2015='39,30', 2016='39,00', 2017='40,90', 2018='41,20'),
 Row(Pays='France', 2005='9,60', 2006='9,30', 2007='10,20', 2008='11,20', 2009='12,20', 2010='12,70', 2011='(1) 12,7', 2012='13,40', 2013='14,00', 2014='14,60', 2015='15,00', 2016='15,70', 2017='16,00', 2018='16,60'),
 Row(Pays='Gr�ce', 2005='7,30', 2006='7,50', 2007='8,20', 2008='8,20', 2009='8,70', 2010='10,10', 2011='11,20', 2012='13,70', 2013='15,30', 2014='15,70', 2015='15,70', 2016='15,40', 2017='17,00', 2018='18,00'),
 Row(Pays='Hongrie', 2005='6,90', 2006='7,40', 2007='8,60', 2008='8,60', 2009='11,70', 2010='12,70', 2011='14,00', 2012='15,50', 2013='16,20', 2014='14,60', 2015='14,50', 2016='14,30', 2017='13,50', 2018='12,50'),
 Row(Pays='Irlande', 2005='2,80', 2006='3,00', 2007='3,50', 2008='3,90', 2009='5,20', 2010='5,70', 2011='6,60', 2012='7,10', 2013='7,60', 2014='8,60', 2015='9,10', 2016='9,30', 2017='10,60', 2018='11,10'),
 Row(Pays='Italie', 2005='7,50', 2006='8,30', 2007='9,80', 2008='11,50', 2009='12,80', 2010='13,00', 2011='12,90', 2012='15,40', 2013='16,70', 2014='17,10', 2015='17,50', 2016='17,40', 2017='18,30', 2018='17,80'),
 Row(Pays='Lettonie', 2005='32,30', 2006='31,10', 2007='29,60', 2008='29,80', 2009='34,30', 2010='30,40', 2011='33,50', 2012='35,70', 2013='37,00', 2014='38,60', 2015='37,50', 2016='37,10', 2017='39,00', 2018='40,30'),
 Row(Pays='Lituanie', 2005='16,80', 2006='16,90', 2007='16,50', 2008='17,80', 2009='19,80', 2010='19,60', 2011='19,90', 2012='21,40', 2013='22,70', 2014='23,60', 2015='25,80', 2016='25,60', 2017='26,00', 2018='24,40'),
 Row(Pays='Luxembourg', 2005='1,40', 2006='1,50', 2007='2,70', 2008='2,80', 2009='2,90', 2010='2,90', 2011='2,90', 2012='3,10', 2013='3,50', 2014='4,50', 2015='5,10', 2016='5,40', 2017='6,30', 2018='9,10'),
 Row(Pays='Malte', 2005='0,10', 2006='0,10', 2007='0,20', 2008='0,20', 2009='0,20', 2010='1,00', 2011='1,90', 2012='2,90', 2013='3,80', 2014='4,70', 2015='5,10', 2016='6,20', 2017='7,30', 2018='8,00'),
 Row(Pays='Pays-Bas', 2005='2,50', 2006='2,80', 2007='3,30', 2008='3,60', 2009='4,30', 2010='3,90', 2011='4,50', 2012='4,70', 2013='4,70', 2014='5,40', 2015='5,70', 2016='5,80', 2017='6,50', 2018='7,40'),
 Row(Pays='Pologne', 2005='6,90', 2006='6,90', 2007='6,90', 2008='7,70', 2009='8,70', 2010='9,30', 2011='10,30', 2012='10,90', 2013='11,40', 2014='11,50', 2015='11,70', 2016='11,30', 2017='11,00', 2018='11,30'),
 Row(Pays='Portugal', 2005='19,50', 2006='20,80', 2007='21,90', 2008='22,90', 2009='24,40', 2010='24,20', 2011='24,60', 2012='24,60', 2013='25,70', 2014='29,50', 2015='30,50', 2016='30,90', 2017='30,60', 2018='30,30'),
 Row(Pays='R�publique tch�que', 2005='7,10', 2006='7,40', 2007='7,90', 2008='8,70', 2009='10,00', 2010='10,50', 2011='10,90', 2012='12,80', 2013='13,90', 2014='15,10', 2015='15,10', 2016='14,90', 2017='14,80', 2018='15,20'),
 Row(Pays='Roumanie', 2005='17,60', 2006='17,10', 2007='18,20', 2008='20,20', 2009='22,20', 2010='22,80', 2011='21,20', 2012='22,80', 2013='23,90', 2014='24,80', 2015='24,80', 2016='25,00', 2017='24,50', 2018='23,90'),
 Row(Pays='Royaume-Uni', 2005='1,10', 2006='1,30', 2007='1,60', 2008='2,70', 2009='3,30', 2010='3,80', 2011='4,30', 2012='4,40', 2013='5,50', 2014='6,70', 2015='8,30', 2016='9,00', 2017='9,70', 2018='11,00'),
 Row(Pays='Slovaquie', 2005='6,40', 2006='6,60', 2007='7,80', 2008='7,70', 2009='9,40', 2010='9,10', 2011='10,30', 2012='10,50', 2013='10,10', 2014='11,70', 2015='12,90', 2016='12,00', 2017='11,50', 2018='11,90'),
 Row(Pays='Slov�nie', 2005='16,00', 2006='15,60', 2007='15,60', 2008='15,00', 2009='20,10', 2010='20,40', 2011='20,30', 2012='20,80', 2013='22,40', 2014='21,50', 2015='21,90', 2016='21,30', 2017='21,10', 2018='21,10'),
 Row(Pays='Su�de', 2005='40,70', 2006='42,40', 2007='43,90', 2008='44,70', 2009='47,90', 2010='47,00', 2011='48,20', 2012='50,20', 2013='50,80', 2014='51,90', 2015='53,00', 2016='53,40', 2017='54,20', 2018='54,60')]

In [23]:
df.toPandas()

,Pays,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Allemagne,"7,20","8,50","10,10","10,10","10,90","11,70","12,50","13,60","13,80","14,40","14,90","14,90","15,50","16,50"
1,Autriche,"24,40","26,30","28,20","28,90","31,00","31,20","31,60","32,70","32,80","33,70","33,50","33,40","33,10","33,40"
2,Belgique,"2,30","2,60","3,10","3,60","4,70","5,60","6,30","7,20","7,50","8,00","8,00","8,70","9,10","9,40"
3,Bulgarie,"9,20","9,40","9,10","10,30","12,00","13,90","14,20","15,80","18,90","18,10","18,30","18,80","18,70","20,50"
4,Chypre,"3,10","3,30","4,00","5,10","5,90","6,20","6,30","7,10","8,50","9,20","9,90","9,90","10,50","13,90"
5,Croatie,"23,70","22,70","22,20","22,00","23,60","25,10","25,40","26,80","28,00","27,80","29,00","28,30","27,30","28,00"
6,Danemark,"16,00","16,30","17,70","18,50","20,00","21,90","23,40","25,50","27,20","29,30","30,80","31,80","34,70","35,70"
7,Espagne,"8,40","9,10","9,70","10,70","13,00","13,80","13,20","14,30","15,30","16,10","16,20","17,40","17,60","17,50"
8,Estonie,"17,40","16,00","17,00","18,60","22,90","24,60","25,30","25,50","25,30","26,10","28,20","28,70","29,10","30,00"
9,Finlande,"28,80","30,10","29,60","31,40","31,30","32,40","32,80","34,40","36,70","38,80","39,30","39,00","40,90","41,20"
10,France,"9,60","9,30","10,20","11,20","12,20","12,70","(1) 12,7","13,40","14,00","14,60","15,00","15,70","16,00","16,60"
11,Gr�ce,"7,30","7,50","8,20","8,20","8,70","10,10","11,20","13,70","15,30","15,70","15,70","15,40","17,00","18,00"
12,Hongrie,"6,90","7,40","8,60","8,60","11,70","12,70","14,00","15,50","16,20","14,60","14,50","14,30","13,50","12,50"
13,Irlande,"2,80","3,00","3,50","3,90","5,20","5,70","6,60","7,10","7,60","8,60","9,10","9,30","10,60","11,10"
14,Italie,"7,50","8,30","9,80","11,50","12,80","13,00","12,90","15,40","16,70","17,10","17,50","17,40","18,30","17,80"
15,Lettonie,"32,30","31,10","29,60","29,80","34,30","30,40","33,50","35,70","37,00","38,60","37,50","37,10","39,00","40,30"
16,Lituanie,"16,80","16,90","16,50","17,80","19,80","19,60","19,90","21,40","22,70","23,60","25,80","25,60","26,00","24,40"
17,Luxembourg,"1,40","1,50","2,70","2,80","2,90","2,90","2,90","3,10","3,50","4,50","5,10","5,40","6,30","9,10"
18,Malte,"0,10","0,10","0,20","0,20","0,20","1,00","1,90","2,90","3,80","4,70","5,10","6,20","7,30","8,00"
19,Pays-Bas,"2,50","2,80","3,30","3,60","4,30","3,90","4,50","4,70","4,70","5,40","5,70","5,80","6,50","7,40"
20,Pologne,"6,90","6,90","6,90","7,70","8,70","9,30","10,30","10,90","11,40","11,50","11,70","11,30","11,00","11,30"
21,Portugal,"19,50","20,80","21,90","22,90","24,40","24,20","24,60","24,60","25,70","29,50","30,50","30,90","30,60","30,30"
22,R�publique tch�que,"7,10","7,40","7,90","8,70","10,00","10,50","10,90","12,80","13,90","15,10","15,10","14,90","14,80","15,20"
23,Roumanie,"17,60","17,10","18,20","20,20","22,20","22,80","21,20","22,80","23,90","24,80","24,80","25,00","24,50","23,90"
24,Royaume-Uni,"1,10","1,30","1,60","2,70","3,30","3,80","4,30","4,40","5,50","6,70","8,30","9,00","9,70","11,00"
25,Slovaquie,"6,40","6,60","7,80","7,70","9,40","9,10","10,30","10,50","10,10","11,70","12,90","12,00","11,50","11,90"
26,Slov�nie,"16,00","15,60","15,60","15,00","20,10","20,40","20,30","20,80","22,40","21,50","21,90","21,30","21,10","21,10"
27,Su�de,"40,70","42,40","43,90","44,70","47,90","47,00","48,20","50,20","50,80","51,90","53,00","53,40","54,20","54,60"

## Chapter 4: Use functions with Spark

In [25]:
from pyspark.sql import functions
print(dir(functions))

['AnalyzeArgument', 'AnalyzeResult', 'Any', 'ArrayType', 'ByteType', 'Callable', 'Column', 'DataType', 'Iterable', 'Mapping', 'NumericType', 'Optional', 'OrderingColumn', 'PandasUDFType', 'ParentDataFrame', 'PartitioningColumn', 'PySparkTypeError', 'PySparkValueError', 'SelectedColumn', 'Sequence', 'SkipRestOfInputTableException', 'StringType', 'StructType', 'TYPE_CHECKING', 'Tuple', 'Type', 'Union', 'UserDefinedFunction', 'UserDefinedTableFunction', 'ValuesView', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'abs', 'acos', 'acosh', 'add_months', 'aes_decrypt', 'aes_encrypt', 'aggregate', 'any_value', 'approxCountDistinct', 'approx_count_distinct', 'approx_percentile', 'array', 'array_agg', 'array_append', 'array_compact', 'array_contains', 'array_distinct', 'array_except', 'array_insert', 'array_intersect', 'array_join', 'array_max', 'array_min', 'array_position', 'array_prepend', 'array_remove', 'array_repeat', 'array_size', 'array_sort', 'array_union', 'arrays_overlap', 'arrays_zip', 'asc', 'asc_nulls_first', 'asc_nulls_last', 'ascii', 'asin', 'asinh', 'assert_true', 'atan', 'atan2', 'atanh', 'avg', 'base64', 'bin', 'bit_and', 'bit_count', 'bit_get', 'bit_length', 'bit_or', 'bit_xor', 'bitmap_bit_position', 'bitmap_bucket_number', 'bitmap_construct_agg', 'bitmap_count', 'bitmap_or_agg', 'bitwiseNOT', 'bitwise_not', 'bool_and', 'bool_or', 'broadcast', 'bround', 'btrim', 'bucket', 'builtin', 'call_function', 'call_udf', 'cardinality', 'cast', 'cbrt', 'ceil', 'ceiling', 'char', 'char_length', 'character_length', 'coalesce', 'col', 'collate', 'collation', 'collect_list', 'collect_set', 'column', 'concat', 'concat_ws', 'contains', 'conv', 'convert_timezone', 'corr', 'cos', 'cosh', 'cot', 'count', 'countDistinct', 'count_distinct', 'count_if', 'count_min_sketch', 'covar_pop', 'covar_samp', 'crc32', 'create_map', 'csc', 'cume_dist', 'curdate', 'current_catalog', 'current_database', 'current_date', 'current_schema', 'current_timestamp', 'current_timezone', 'current_user', 'date_add', 'date_diff', 'date_format', 'date_from_unix_date', 'date_part', 'date_sub', 'date_trunc', 'dateadd', 'datediff', 'datepart', 'day', 'dayname', 'dayofmonth', 'dayofweek', 'dayofyear', 'days', 'decimal', 'decode', 'degrees', 'dense_rank', 'desc', 'desc_nulls_first', 'desc_nulls_last', 'e', 'element_at', 'elt', 'encode', 'endswith', 'equal_null', 'every', 'exists', 'exp', 'explode', 'explode_outer', 'expm1', 'expr', 'extract', 'factorial', 'filter', 'find_in_set', 'first', 'first_value', 'flatten', 'floor', 'forall', 'format_number', 'format_string', 'from_csv', 'from_json', 'from_unixtime', 'from_utc_timestamp', 'from_xml', 'functools', 'get', 'get_json_object', 'getbit', 'greatest', 'grouping', 'grouping_id', 'hash', 'hex', 'histogram_numeric', 'hll_sketch_agg', 'hll_sketch_estimate', 'hll_union', 'hll_union_agg', 'hour', 'hours', 'hypot', 'ifnull', 'ilike', 'initcap', 'inline', 'inline_outer', 'input_file_block_length', 'input_file_block_start', 'input_file_name', 'inspect', 'instr', 'is_valid_utf8', 'is_variant_null', 'isnan', 'isnotnull', 'isnull', 'java_method', 'json_array_length', 'json_object_keys', 'json_tuple', 'kurtosis', 'lag', 'last', 'last_day', 'last_value', 'lcase', 'lead', 'least', 'left', 'length', 'levenshtein', 'like', 'listagg', 'listagg_distinct', 'lit', 'ln', 'localtimestamp', 'locate', 'log', 'log10', 'log1p', 'log2', 'lower', 'lpad', 'ltrim', 'make_date', 'make_dt_interval', 'make_interval', 'make_timestamp', 'make_timestamp_ltz', 'make_timestamp_ntz', 'make_valid_utf8', 'make_ym_interval', 'map_concat', 'map_contains_key', 'map_entries', 'map_filter', 'map_from_arrays', 'map_from_entries', 'map_keys', 'map_values', 'map_zip_with', 'mask', 'max', 'max_by', 'md5', 'mean', 'median', 'min', 'min_by', 'minute', 'mode', 'monotonically_increasing_id', 'month', 'monthname', 'months', 'months_between', 'named_struct', 'nanvl', 'negate', 'negative', 'next_day', 'now', 'nth_value', 'ntile', 'nullif', 'nullifzero', 'nvl', 'nvl2', 'octet_length', 'overlay', 'overload', 'pandas_udf', 'parse_json', 'parse_url', 'partitioning', 'percent_rank', 'percentile', 'percentile_approx', 'pi', 'pmod', 'posexplode', 'posexplode_outer', 'position', 'positive', 'pow', 'power', 'printf', 'product', 'quarter', 'radians', 'raise_error', 'rand', 'randn', 'randstr', 'rank', 'reduce', 'reflect', 'regexp', 'regexp_count', 'regexp_extract', 'regexp_extract_all', 'regexp_instr', 'regexp_like', 'regexp_replace', 'regexp_substr', 'regr_avgx', 'regr_avgy', 'regr_count', 'regr_intercept', 'regr_r2', 'regr_slope', 'regr_sxx', 'regr_sxy', 'regr_syy', 'repeat', 'replace', 'reverse', 'right', 'rint', 'rlike', 'round', 'row_number', 'rpad', 'rtrim', 'schema_of_csv', 'schema_of_json', 'schema_of_variant', 'schema_of_variant_agg', 'schema_of_xml', 'sec', 'second', 'sentences', 'sequence', 'session_user', 'session_window', 'sha', 'sha1', 'sha2', 'shiftLeft', 'shiftRight', 'shiftRightUnsigned', 'shiftleft', 'shiftright', 'shiftrightunsigned', 'shuffle', 'sign', 'signum', 'sin', 'sinh', 'size', 'skewness', 'slice', 'some', 'sort_array', 'soundex', 'spark_partition_id', 'split', 'split_part', 'sqrt', 'stack', 'startswith', 'std', 'stddev', 'stddev_pop', 'stddev_samp', 'str_to_map', 'string_agg', 'string_agg_distinct', 'struct', 'substr', 'substring', 'substring_index', 'sum', 'sumDistinct', 'sum_distinct', 'sys', 'tan', 'tanh', 'timestamp_add', 'timestamp_diff', 'timestamp_micros', 'timestamp_millis', 'timestamp_seconds', 'toDegrees', 'toRadians', 'to_binary', 'to_char', 'to_csv', 'to_date', 'to_json', 'to_number', 'to_timestamp', 'to_timestamp_ltz', 'to_timestamp_ntz', 'to_unix_timestamp', 'to_utc_timestamp', 'to_varchar', 'to_variant_object', 'to_xml', 'transform', 'transform_keys', 'transform_values', 'translate', 'trim', 'trunc', 'try_add', 'try_aes_decrypt', 'try_avg', 'try_divide', 'try_element_at', 'try_make_interval', 'try_make_timestamp', 'try_make_timestamp_ltz', 'try_make_timestamp_ntz', 'try_mod', 'try_multiply', 'try_parse_json', 'try_parse_url', 'try_reflect', 'try_subtract', 'try_sum', 'try_to_binary', 'try_to_number', 'try_to_timestamp', 'try_url_decode', 'try_validate_utf8', 'try_variant_get', 'typeof', 'ucase', 'udf', 'udtf', 'unbase64', 'unhex', 'uniform', 'unix_date', 'unix_micros', 'unix_millis', 'unix_seconds', 'unix_timestamp', 'unwrap_udt', 'upper', 'url_decode', 'url_encode', 'user', 'validate_utf8', 'var_pop', 'var_samp', 'variance', 'variant_get', 'version', 'warnings', 'weekday', 'weekofyear', 'when', 'width_bucket', 'window', 'window_time', 'xpath', 'xpath_boolean', 'xpath_double', 'xpath_float', 'xpath_int', 'xpath_long', 'xpath_number', 'xpath_short', 'xpath_string', 'xxhash64', 'year', 'years', 'zeroifnull', 'zip_with']

In [26]:
help(abs)

Help on built-in function abs in module builtins:

abs(x, /)
    Return the absolute value of the argument.

In [27]:
schema = StructType().add("id_utilisateur", "string").add("pays", "string").add("profession", "string").add("genre", 'string').add("age", "integer")
df = spark.createDataFrame([("A123", 'Maroc', "Médecin", "Femme", 33), ("B234", 'Canada', "Entrepreneur", "Femme", 35), ("C345", 'France', "Professeur", "Homme", 41)],schema=schema)
df.show()

+--------------+------+------------+-----+---+
|id_utilisateur|  pays|  profession|genre|age|
+--------------+------+------------+-----+---+
|          A123| Maroc|     Médecin|Femme| 33|
|          B234|Canada|Entrepreneur|Femme| 35|
|          C345|France|  Professeur|Homme| 41|
+--------------+------+------------+-----+---+

In [28]:
from pyspark.sql.functions import lower, upper, col, substring
df.select(lower(col('pays'))).show()

+-----------+
|lower(pays)|
+-----------+
|      maroc|
|     canada|
|     france|
+-----------+

In [31]:
df.select(lower(col('pays')), upper(col('pays')), substring(col('pays'), 1, 3)).show(5)

+-----------+-----------+---------------------+
|lower(pays)|upper(pays)|substring(pays, 1, 3)|
+-----------+-----------+---------------------+
|      maroc|      MAROC|                  Mar|
|     canada|     CANADA|                  Can|
|     france|     FRANCE|                  Fra|
+-----------+-----------+---------------------+

In [32]:
from pyspark.sql.functions import avg
df.select(avg(col('Age'))).show()

+------------------+
|          avg(Age)|
+------------------+
|36.333333333333336|
+------------------+

In [33]:
from pyspark.sql.functions import soundex
df.select(soundex(df.pays).alias("soundex")).show()

+-------+
|soundex|
+-------+
|   M620|
|   C530|
|   F652|
+-------+

In [34]:
df1 = spark.createDataFrame((("2021-01-23", 1), ("2021-06-24", 2), ("2021-09-20", 3)), ("date", "nombre_de_mois"))
df1.show()

+----------+--------------+
|      date|nombre_de_mois|
+----------+--------------+
|2021-01-23|             1|
|2021-06-24|             2|
|2021-09-20|             3|
+----------+--------------+

In [36]:
import pyspark.sql.functions as F
df1.withColumn("nouvelle_date", F.add_months(col("date"), df1.first()[1])).show()

+----------+--------------+-------------+
|      date|nombre_de_mois|nouvelle_date|
+----------+--------------+-------------+
|2021-01-23|             1|   2021-02-23|
|2021-06-24|             2|   2021-07-24|
|2021-09-20|             3|   2021-10-20|
+----------+--------------+-------------+

In [41]:
df2 = spark.createDataFrame([("2021_01_11",)], ["date"])
df2.show()

+----------+
|      date|
+----------+
|2021_01_11|
+----------+

In [39]:
df2.printSchema()

root
 |-- date: string (nullable = true)

In [42]:
from pyspark.sql.functions import to_date

df3 = df2.withColumn('date', to_date(df2.date, 'yyyy_MM_dd'))
df3.printSchema()
df3.select("date").dtypes

root
 |-- date: date (nullable = true)

[('date', 'date')]

In [44]:
df3.select(F.date_format('date','MM-dd-yyy').alias('Format date')).show()

+-----------+
|Format date|
+-----------+
| 01-11-2021|
+-----------+

In [45]:
def cat_age(age):
  if age<40:
    return "Categorie 1"
  else:
    return "Categorie 2"

In [49]:
from pyspark.sql.functions import udf
age_udf=udf(cat_age,StringType())
df.withColumn("age_cat",age_udf(col("age"))).groupby("age_cat").count().show()

+-----------+-----+
|    age_cat|count|
+-----------+-----+
|Categorie 1|    2|
|Categorie 2|    1|
+-----------+-----+

In [50]:
a = [('chat', 1), ('chien', 2), ('singe', 3), ('lion', 4)]
df_a = spark.createDataFrame(a, ['animal', 'id'])

b = [('tigre', 1), ('chat', 2), ('singe', 3), ('girafe', 4)]
df_b = spark.createDataFrame(b, ['animal', 'id'])

df_a.show()
df_b.show()

+------+---+
|animal| id|
+------+---+
|  chat|  1|
| chien|  2|
| singe|  3|
|  lion|  4|
+------+---+

+------+---+
|animal| id|
+------+---+
| tigre|  1|
|  chat|  2|
| singe|  3|
|girafe|  4|
+------+---+

In [51]:
j_interne= df_a.join(df_b,df_a.animal==df_b.animal)
j_interne.show()

+------+---+------+---+
|animal| id|animal| id|
+------+---+------+---+
|  chat|  1|  chat|  2|
| singe|  3| singe|  3|
+------+---+------+---+

In [52]:
j_gauche= df_a.join(df_b,df_a.animal==df_b.animal, how='left')
j_gauche.show()

+------+---+------+----+
|animal| id|animal|  id|
+------+---+------+----+
| chien|  2|  NULL|NULL|
|  chat|  1|  chat|   2|
|  lion|  4|  NULL|NULL|
| singe|  3| singe|   3|
+------+---+------+----+

In [53]:
j_droite= df_a.join(df_b,df_a.animal==df_b.animal, how='right')
j_droite.show()

+------+----+------+---+
|animal|  id|animal| id|
+------+----+------+---+
|  chat|   1|  chat|  2|
|  NULL|NULL| tigre|  1|
| singe|   3| singe|  3|
|  NULL|NULL|girafe|  4|
+------+----+------+---+

## Chapter 5: Discover and use the RDD

RDD : Resilient Distributed Datasets

In [54]:
from google.colab import files
files.upload()

Saving texte.txt to texte.txt

{'texte.txt': b'Les RDD sont utiles pour le traitement des donn\xc3\xa9es non structur\xc3\xa9es'}

In [55]:
rdd=sc.textFile("texte.txt")
type(rdd)

pyspark.core.rdd.RDD

In [56]:
rdd.collect()

['Les RDD sont utiles pour le traitement des données non structurées']

In [57]:
import numpy as np
liste=np.random.randint(0,100,10)
liste

array([37, 87, 34, 15, 34, 78, 75, 59, 43, 72])

In [58]:
rdd_2=sc.parallelize(liste)

In [59]:
rdd_2.glom().collect()

[[np.int64(37), np.int64(87), np.int64(34), np.int64(15), np.int64(34)],
 [np.int64(78), np.int64(75), np.int64(59), np.int64(43), np.int64(72)]]

In [60]:
rdd_2.count()

10

In [61]:
rdd_2.first()

np.int64(37)

In [62]:
rdd=sc.parallelize(range(1,10))

In [64]:
rdd_1=rdd.map(lambda x: (x,'a'*x))
rdd_1.collect()

[(1, 'a'),
 (2, 'aa'),
 (3, 'aaa'),
 (4, 'aaaa'),
 (5, 'aaaaa'),
 (6, 'aaaaaa'),
 (7, 'aaaaaaa'),
 (8, 'aaaaaaaa'),
 (9, 'aaaaaaaaa')]

In [65]:
rdd_2=rdd.filter(lambda x: x%2==0)
rdd_2.collect()

[2, 4, 6, 8]

In [67]:
rdd_3=rdd.flatMap(lambda x: [(x,2*x),(-x,3*x)])
rdd_3.collect()

[(1, 2),
 (-1, 3),
 (2, 4),
 (-2, 6),
 (3, 6),
 (-3, 9),
 (4, 8),
 (-4, 12),
 (5, 10),
 (-5, 15),
 (6, 12),
 (-6, 18),
 (7, 14),
 (-7, 21),
 (8, 16),
 (-8, 24),
 (9, 18),
 (-9, 27)]

## Chapter 6: MLlib

In [74]:
import pandas as pd

df = pd.DataFrame({'Salarié': ['Eric', 'Elise', 'Hapsa', 'Xin'], 'Genre': ['Homme', 'Femme', 'Femme', 'Homme'], 'groupe': ['Technicien',  'Ingénieur','PhD',
     'Technicien'],'date_embauche': [2016, 1988, 2012, 2001], 'salaire': [30000, 100000, 60000, 60000]})
df

  Salarié  Genre      groupe  date_embauche  salaire
0    Eric  Homme  Technicien           2016    30000
1   Elise  Femme   Ingénieur           1988   100000
2   Hapsa  Femme         PhD           2012    60000
3     Xin  Homme  Technicien           2001    60000

In [75]:
df1 = spark.createDataFrame(df)
df1.show()

+-------+-----+----------+-------------+-------+
|Salarié|Genre|    groupe|date_embauche|salaire|
+-------+-----+----------+-------------+-------+
|   Eric|Homme|Technicien|         2016|  30000|
|  Elise|Femme| Ingénieur|         1988| 100000|
|  Hapsa|Femme|       PhD|         2012|  60000|
|    Xin|Homme|Technicien|         2001|  60000|
+-------+-----+----------+-------------+-------+

In [76]:
from pyspark.ml.feature import StringIndexer
Genre_index = StringIndexer(inputCol="Genre", outputCol="Genre_num").fit(df1)
df1 = Genre_index.transform(df1)
df1.show()

+-------+-----+----------+-------------+-------+---------+
|Salarié|Genre|    groupe|date_embauche|salaire|Genre_num|
+-------+-----+----------+-------------+-------+---------+
|   Eric|Homme|Technicien|         2016|  30000|      1.0|
|  Elise|Femme| Ingénieur|         1988| 100000|      0.0|
|  Hapsa|Femme|       PhD|         2012|  60000|      0.0|
|    Xin|Homme|Technicien|         2001|  60000|      1.0|
+-------+-----+----------+-------------+-------+---------+

In [78]:
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-2.3.1-bin-hadoop2.7"

import findspark
findspark.init()
from pyspark import SparkContext

sc = SparkContext.getOrCreate()

import pyspark
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

In [79]:
import pandas as pd
d = {'x': [7, 17, 27, 37, 47, 57], 'y': [7, 18, 16, 24, 22, 30], 'z': [17, 12, 19, 24, 22, 45]}
df = pd.DataFrame(data=d)
df1=spark.createDataFrame(df)
df1.show()

+---+---+---+
|  x|  y|  z|
+---+---+---+
|  7|  7| 17|
| 17| 18| 12|
| 27| 16| 19|
| 37| 24| 24|
| 47| 22| 22|
| 57| 30| 45|
+---+---+---+

In [80]:
from pyspark.ml.feature import VectorAssembler
assembleur = VectorAssembler(inputCols=df1.columns, outputCol="caractéristiques")
df_nouv=assembleur.transform(df1)
df_nouv.show()

+---+---+---+----------------+
|  x|  y|  z|caractéristiques|
+---+---+---+----------------+
|  7|  7| 17|  [7.0,7.0,17.0]|
| 17| 18| 12|[17.0,18.0,12.0]|
| 27| 16| 19|[27.0,16.0,19.0]|
| 37| 24| 24|[37.0,24.0,24.0]|
| 47| 22| 22|[47.0,22.0,22.0]|
| 57| 30| 45|[57.0,30.0,45.0]|
+---+---+---+----------------+

In [81]:
from pyspark.ml.feature import MinMaxScaler

scaler = MinMaxScaler (inputCol="caractéristiques", outputCol="mise_à_l_échelle")

scaler_model = scaler.fit(df_nouv)
scaled_data = scaler_model.transform(df_nouv)
scaled_data.select("caractéristiques",'mise_à_l_échelle').show(truncate=False)

+----------------+--------------------------------------------+
|caractéristiques|mise_à_l_échelle                            |
+----------------+--------------------------------------------+
|[7.0,7.0,17.0]  |[0.0,0.0,0.15151515151515152]               |
|[17.0,18.0,12.0]|[0.2,0.4782608695652174,0.0]                |
|[27.0,16.0,19.0]|[0.4,0.3913043478260869,0.21212121212121213]|
|[37.0,24.0,24.0]|[0.6,0.7391304347826086,0.36363636363636365]|
|[47.0,22.0,22.0]|[0.8,0.6521739130434783,0.30303030303030304]|
|[57.0,30.0,45.0]|[1.0,1.0,1.0]                               |
+----------------+--------------------------------------------+

In [82]:
import pandas as pd
d = {'x': [7, 17, 27, 37, 47, 57], 'y': [7, 18, 16, 24, 22, 30]}
df = pd.DataFrame(data=d)
df1=spark.createDataFrame(df)
df1.show()

+---+---+
|  x|  y|
+---+---+
|  7|  7|
| 17| 18|
| 27| 16|
| 37| 24|
| 47| 22|
| 57| 30|
+---+---+

In [83]:
from pyspark.ml.feature import VectorAssembler
assembleur = VectorAssembler(inputCols=df1.columns, outputCol="caractéristiques")
df_nouv=assembleur.transform(df1)
df_nouv.show()

+---+---+----------------+
|  x|  y|caractéristiques|
+---+---+----------------+
|  7|  7|       [7.0,7.0]|
| 17| 18|     [17.0,18.0]|
| 27| 16|     [27.0,16.0]|
| 37| 24|     [37.0,24.0]|
| 47| 22|     [47.0,22.0]|
| 57| 30|     [57.0,30.0]|
+---+---+----------------+

In [84]:
from pyspark.ml.stat import Correlation
pearson_corr = Correlation.corr(df_nouv,'caractéristiques')
pearson_corr.show(2,False)

+----------------------------------------------------------------------------------+
|pearson(caractéristiques)                                                         |
+----------------------------------------------------------------------------------+
|1.0                 0.9201575383978458  \n0.9201575383978458  1.0                 |
+----------------------------------------------------------------------------------+

In [85]:
spearman_corr=Correlation.corr(df_nouv,'caractéristiques',"spearman")
spearman_corr.show(2,False)

+----------------------------------------------------------------------------------+
|spearman(caractéristiques)                                                        |
+----------------------------------------------------------------------------------+
|1.0                 0.8857142857142858  \n0.8857142857142858  1.0                 |
+----------------------------------------------------------------------------------+

In [86]:
import pandas as pd
d = {'x': [7, 17, 27, 37, 47, 57,67,77,87,97,107,117,127,137, 147], 'label': [7, 18, 16, 24, 22, 30, 28, 36, 34, 42, 40, 48, 46, 54, 52]}
df = pd.DataFrame(data=d)
df1=spark.createDataFrame(df)
df1.columns

['x', 'label']

In [87]:
from pyspark.ml.linalg import Vector
from pyspark.ml.feature import VectorAssembler

assembleur=VectorAssembler(inputCols=['x'],outputCol='features')
df_nouv=assembleur.transform(df1)
df_nouv.printSchema()

root
 |-- x: long (nullable = true)
 |-- label: long (nullable = true)
 |-- features: vector (nullable = true)

In [88]:
df_nouv.select(['features','label']).show()

+--------+-----+
|features|label|
+--------+-----+
|   [7.0]|    7|
|  [17.0]|   18|
|  [27.0]|   16|
|  [37.0]|   24|
|  [47.0]|   22|
|  [57.0]|   30|
|  [67.0]|   28|
|  [77.0]|   36|
|  [87.0]|   34|
|  [97.0]|   42|
| [107.0]|   40|
| [117.0]|   48|
| [127.0]|   46|
| [137.0]|   54|
| [147.0]|   52|
+--------+-----+

In [89]:
appr, test = df_nouv.randomSplit([0.75, 0.25])
print(f"Taille données d'apprentissage : {appr.count()}" )
print(f"Taille données de test : {test.count()}" )

Taille données d'apprentissage : 10
Taille données de test : 5

In [90]:
from pyspark.ml.regression import LinearRegression
lr = LinearRegression()
lr_model = lr.fit(appr)

In [91]:
pred_df=lr_model.transform(test)
pred_df.show()

+---+-----+--------+------------------+
|  x|label|features|        prediction|
+---+-----+--------+------------------+
| 37|   24|  [37.0]|20.491317238458244|
| 47|   22|  [47.0]|23.642100804743723|
| 57|   30|  [57.0]|26.792884371029203|
| 67|   28|  [67.0]|29.943667937314682|
|107|   40| [107.0]|  42.5468022024566|
+---+-----+--------+------------------+